# set `baseurl` to your root domain
# Should be without the www. otherwise issues with CORS might happen
baseurl = "https://bigelectrons.com/"  # Include trailing slash
# title = "Clarity"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright Â© 2018 - 2022 @ https://github.com/Joesan"
# canonifyurls = true
paginate = 10
#theme = "github.com/chipzoller/hugo-clarity"
theme = "hugo-clarity"
#disqusShortname = ""
enableEmoji = true

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
#series = "series"
